substitutions:
    devicename: jt_appendiabiti
    data_intro: JT_
    relay_descriptor: luce_appendiabiti

esphome:
  name: $devicename
  platform: ESP8266
  board: esp01_1m
wifi:
  ssid: !secret SSID
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${devicename} Fallback Hotspot
    password: !secret wifi_password 

captive_portal:

# Enable logging
logger:
   baud_rate: 0
    # Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time
  - platform: sntp
    on_time:
      # Every 5 minutes
      - seconds: 0
        minutes: /5
        then:
            - if:
                condition: 
                  switch.is_on: r_${data_intro}_${relay_descriptor}
                then:
                  - logger.log: "Switch refreshed with ON state"
                  - uart.write: [0xA0, 0x01, 0x01, 0xA2]
                else:
                  - logger.log: "Switch refreshed with OFF state"
                  - uart.write: [0xA0, 0x01, 0x00, 0xA1]
uart:
  rx_pin: RX 
  tx_pin: TX 
  baud_rate: 9600


switch:
  - platform: restart
    name: ${data_intro} ESP32 Restart
  - platform: template
    name: ${data_intro} ${relay_descriptor}
    id: r_${data_intro}_${relay_descriptor}
    restore_state: true
    turn_on_action:
      - uart.write: [0xA0, 0x01, 0x01, 0xA2]
    turn_off_action:
      - uart.write: [0xA0, 0x01, 0x00, 0xA1]
    optimistic: true
    assumed_state: true
# Enable Home Assistant API
api:
     password: !secret api_password

ota:
     safe_mode: True
     password: !secret ota_password

web_server:
  port: 80

